export const GET_TOP_MOVIES = 'GET_TOP_MOVIES';
export const SET_ACTIVE_ID = 'SET_ACTIVE_ID';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const REMOVE_ACTIVE_ID = 'REMOVE_ACTIVE_ID';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
